import { FormEvent, ReactNode, useEffect, useState } from 'react';
import { Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpen, BriefcaseBusiness, CalendarDays, CheckCircle2, ClipboardList, FileCheck2, FileText, GraduationCap, Headphones, LayoutDashboard, LockKeyhole, LogOut, Menu, ShieldCheck, Upload, UserCheck, Users, X } from 'lucide-react';
import type { Session } from '@supabase/supabase-js';
import { isSupabaseConfigured, supabase } from './lib/supabase';

type Role = 'owner_admin'|'tax_preparer'|'tax_client'|'support_staff';
type Profile = {id:string; full_name:string; role:Role; status:string};
const skoolUrl = import.meta.env.VITE_SKOOL_COMMUNITY_URL || 'https://www.skool.com/tsc-elite-tax-pros';
const bookingUrl = 'https://calendly.com/tina_stylez_customs';
const consultationEmail = 'tsc.elite.assist@gmail.com';
const consultationEmailUrl = `mailto:${consultationEmail}?subject=${encodeURIComponent('TSC Elite Tax Consultation Request')}`;
const roleNames:Record<Role,string>={owner_admin:'Owner / Admin',tax_preparer:'Tax Preparer',tax_client:'Tax Client',support_staff:'Support Staff'};

function Header(){const [open,setOpen]=useState(false);return <header className="header"><Link to="/" className="brand"><span className="crest">TSC</span><span><b>TSC ELITE</b><small>TAX SERVICE BUREAU</small></span></Link><button className="menu" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}><Link to="/services">Services</Link><Link to="/preparers">For Tax Preparers</Link><Link to="/clients">For Clients</Link><a href={skoolUrl} target="_blank" rel="noreferrer">Tax Academy</a><Link className="nav-login" to="/login">Portal Login</Link></nav></header>}
function Footer(){return <footer><div className="brand light"><span className="crest">TSC</span><span><b>TSC ELITE</b><small>TAX SERVICE BUREAU</small></span></div><p>Tax excellence. Legacy building. Empowerment.</p><div><a href={consultationEmailUrl}>{consultationEmail}</a><a href="tel:+19292775331">929-277-5331</a></div><small>© {new Date().getFullYear()} TSC Elite Assist Tax Pro LLC. All rights reserved.</small></footer>}
function PublicLayout({children}:{children:ReactNode}){return <><Header/><main>{children}</main><Footer/></>}

function Home(){return <PublicLayout><section className="hero"><div className="hero-copy"><span className="eyebrow">TSC ELITE TAX SERVICE BUREAU</span><h1>Build your tax legacy with confidence.</h1><p>Professional tax preparation for clients. Software, mentorship, training and backend support for tax professionals.</p><div className="actions"><Link className="btn gold" to="/clients">File With Us <ArrowRight/></Link><Link className="btn outline" to="/preparers">Join Our Bureau</Link></div><div className="trust"><span><ShieldCheck/>Secure process</span><span><UserCheck/>Professional support</span><span><GraduationCap/>Training available</span></div></div><div className="hero-art"><img src="/assets/tsc-bureau.png" alt="TSC Elite Tax Service Bureau"/></div></section><section className="split-intro"><p className="eyebrow">ONE BUREAU. TWO PATHS.</p><h2>Choose the support built for you.</h2><div className="path-grid"><article><FileCheck2/><h3>I need my taxes prepared</h3><p>Start securely, upload requested documents and follow your return from intake through completion.</p><Link to="/clients">Client Services <ArrowRight/></Link></article><article><BriefcaseBusiness/><h3>I’m building a tax business</h3><p>Access professional software, mentorship, compliance guidance and an active tax-business community.</p><Link to="/preparers">Preparer Opportunities <ArrowRight/></Link></article></div></section><section className="feature-band"><div><span className="stat">01</span><h3>White-Labeled Software</h3><p>Offer your own branded tax solutions with reliable backend support.</p></div><div><span className="stat">02</span><h3>EFIN/PTIN Mentorship</h3><p>Guidance from application through compliant business growth.</p></div><div><span className="stat">03</span><h3>Community Leadership</h3><p>Build trusted relationships and create meaningful local impact.</p></div></section><section className="cta"><div><p className="eyebrow">MASTERY. MENTORSHIP. GROWTH.</p><h2>Your next tax season starts now.</h2></div><a className="btn gold" href={bookingUrl} target="_blank" rel="noreferrer">Book a Consultation <CalendarDays/></a></section></PublicLayout>}

function Clients(){return <PublicLayout><PageHero kicker="FOR TAX CLIENTS" title="Tax filing with clarity, confidentiality and support." text="Complete your intake online, send documents securely and stay informed throughout the process."/><section className="steps"><Step n="1" icon={<ClipboardList/>} title="Complete your intake" text="Tell us about your tax situation and household."/><Step n="2" icon={<Upload/>} title="Submit documents" text="Use your private portal for requested files."/><Step n="3" icon={<FileCheck2/>} title="Review and approve" text="Your preparer reviews the return with you before filing."/></section><section className="center"><Link className="btn gold" to="/register?role=tax_client">Create Client Account</Link><Link className="text-link" to="/login">Already registered? Sign in</Link></section></PublicLayout>}
function Preparers(){return <PublicLayout><PageHero kicker="FOR TAX PROFESSIONALS" title="Launch and grow your tax business with a bureau behind you." text="Get the infrastructure, mentorship and community support you need to serve clients professionally."/><section className="cards"><Card icon={<LayoutDashboard/>} title="Professional Software" text="A business-ready system for managing your workflow and serving clients."/><Card icon={<GraduationCap/>} title="Tax Academy" text="Structured training, onboarding and continuing tax-season education in Skool."/><Card icon={<Headphones/>} title="Backend Support" text="Operational guidance, technical help and escalation support when you need it."/><Card icon={<Users/>} title="Elite Community" text="Connect with serious tax business owners focused on mastery and growth."/></section><section className="website-service"><img src="/assets/professional-tax-websites.png" alt="Professional tax websites built for tax preparers and service bureaus"/><div><p className="eyebrow">WEBSITE DEVELOPMENT</p><h2>Need a professional website for your tax business?</h2><p>We build polished, mobile-friendly tax websites that help you establish trust, showcase your services and let clients book consultations online.</p><ul><li>Custom tax-business branding</li><li>Consultation booking integration</li><li>Service and contact pages</li><li>Mobile-ready professional design</li></ul><a className="btn gold" href={consultationEmailUrl}>Request a Website Consultation <ArrowRight/></a></div></section><section className="center"><Link className="btn gold" to="/apply">Apply to Join the Bureau</Link><a className="text-link" href={skoolUrl} target="_blank" rel="noreferrer">Explore the Tax Community</a></section></PublicLayout>}
function Services(){return <PublicLayout><PageHero kicker="OUR SERVICES" title="A complete tax-service ecosystem." text="Support for taxpayers, preparers and growing tax offices—all under one professional bureau."/><section className="service-list"><Card icon={<FileText/>} title="Individual Tax Preparation" text="Remote, organized tax preparation with secure client communication."/><Card icon={<BriefcaseBusiness/>} title="Service Bureau Partnership" text="Software, operational support and scalable resources for tax professionals."/><Card icon={<BookOpen/>} title="Tax Education" text="Courses, live training and practical business-building resources."/></section></PublicLayout>}
function PageHero({kicker,title,text}:{kicker:string;title:string;text:string}){return <section className="page-hero"><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{text}</p></section>}
function Step({n,icon,title,text}:{n:string;icon:ReactNode;title:string;text:string}){return <article className="step"><span>{n}</span>{icon}<h3>{title}</h3><p>{text}</p></article>}
function Card({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <article className="card">{icon}<h3>{title}</h3><p>{text}</p></article>}

function Login(){const nav=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();if(!isSupabaseConfigured){setMessage('Connect Supabase to activate secure sign-in.');return}const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else nav('/dashboard')}return <PublicLayout><AuthCard title="Welcome back" sub="Sign in to your secure TSC Elite portal."><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{message&&<p className="form-message">{message}</p>}<button className="btn gold full">Secure Sign In <LockKeyhole/></button></form><p className="form-foot">New client? <Link to="/register?role=tax_client">Create an account</Link></p></AuthCard></PublicLayout>}
function Register(){const nav=useNavigate();const params=new URLSearchParams(location.search);const requested=params.get('role')==='tax_preparer'?'tax_preparer':'tax_client';const [form,setForm]=useState({name:'',email:'',phone:'',password:'',role:requested});const [message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();if(!isSupabaseConfigured){setMessage('Connect Supabase to activate account registration.');return}const {error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{full_name:form.name,phone:form.phone,requested_role:form.role}}});if(error)setMessage(error.message);else {setMessage('Check your email to confirm your account.');setTimeout(()=>nav('/login'),1600)}}return <PublicLayout><AuthCard title="Create your account" sub="Each user receives private credentials and protected access."><form onSubmit={submit}><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input type="tel" required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Password<input type="password" minLength={10} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{message&&<p className="form-message">{message}</p>}<button className="btn gold full">Create Secure Account</button></form></AuthCard></PublicLayout>}
function Apply(){const [sent,setSent]=useState(false);const [message,setMessage]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(!isSupabaseConfigured){setMessage('Your application form is ready. Connect Supabase to accept submissions.');return}const {error}=await supabase.from('preparer_applications').insert(data);if(error)setMessage(error.message);else setSent(true)}if(sent)return <PublicLayout><section className="success"><CheckCircle2/><h1>Application received.</h1><p>Our team will review your information and contact you with the next step.</p><Link className="btn gold" to="/">Return Home</Link></section></PublicLayout>;return <PublicLayout><PageHero kicker="BUREAU APPLICATION" title="Tell us about your tax-business goals." text="Complete the application below. Submission does not guarantee acceptance."/><form className="application" onSubmit={submit}><div className="form-grid"><label>Full legal name<input name="full_name" required/></label><label>Email<input name="email" type="email" required/></label><label>Phone<input name="phone" type="tel" required/></label><label>Business name<input name="business_name"/></label><label>PTIN status<select name="ptin_status" required><option value="">Select one</option><option>Active PTIN</option><option>Applying for PTIN</option><option>Need guidance</option></select></label><label>EFIN status<select name="efin_status" required><option value="">Select one</option><option>Active EFIN</option><option>Applying for EFIN</option><option>Need guidance</option></select></label><label>Years preparing returns<input name="experience_years" type="number" min="0"/></label><label>Estimated clients this season<input name="estimated_clients" type="number" min="0"/></label></div><label>What support are you looking for?<textarea name="goals" rows={5} required/></label><label className="check"><input name="consent" type="checkbox" required/>I certify that this information is accurate and consent to being contacted.</label>{message&&<p className="form-message">{message}</p>}<button className="btn gold">Submit Application <ArrowRight/></button></form></PublicLayout>}
function AuthCard({title,sub,children}:{title:string;sub:string;children:ReactNode}){return <section className="auth-wrap"><div className="auth-card"><span className="crest large">TSC</span><h1>{title}</h1><p>{sub}</p>{children}</div></section>}

function Dashboard({session}:{session:Session}){const [profile,setProfile]=useState<Profile|null>(null);useEffect(()=>{supabase.from('profiles').select('id,full_name,role,status').eq('id',session.user.id).single().then(({data})=>setProfile(data as Profile))},[session]);const role=profile?.role||'tax_client';const items=role==='owner_admin'?[['Active Preparers','24'],['Open Applications','8'],['Active Clients','146'],['Support Tickets','5']]:role==='tax_preparer'?[['Assigned Clients','18'],['Documents Pending','7'],['Returns In Review','4'],['Completed','29']]:role==='support_staff'?[['Open Tickets','5'],['Awaiting Response','3'],['Resolved Today','11'],['Escalations','1']]:[['Return Status','Intake Started'],['Documents','2 Received'],['Messages','1 New'],['Next Step','Complete Intake']];return <div className="portal"><aside><div className="brand light"><span className="crest">TSC</span><span><b>TSC ELITE</b><small>TAX PORTAL</small></span></div><nav><a className="active"><LayoutDashboard/>Overview</a><a><Users/>Accounts</a><a><FileText/>Documents</a><a><ClipboardList/>Tasks</a><a><Headphones/>Support</a></nav><button onClick={()=>supabase.auth.signOut()}><LogOut/>Sign Out</button></aside><section className="portal-main"><div className="portal-head"><div><p>{roleNames[role]}</p><h1>Welcome, {profile?.full_name||session.user.user_metadata.full_name||'TSC Member'}</h1></div><span className="secure"><ShieldCheck/>Secure portal</span></div><div className="metric-grid">{items.map(([a,b])=><article key={a}><span>{a}</span><strong>{b}</strong></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Priority actions</h2><ClipboardList/></div><ul><li><span>Complete required profile information</span><button>Open</button></li><li><span>Review new document requests</span><button>Review</button></li><li><span>Check portal messages</span><button>View</button></li></ul></section><section className="panel accent"><BookOpen/><h2>Tax Academy</h2><p>Training, resources and bureau announcements are available in the private Skool community.</p><a className="btn pale" href={skoolUrl} target="_blank" rel="noreferrer">Open Skool Community</a></section></div></section></div>}

export default function App(){const [session,setSession]=useState<Session|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);return <Routes><Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/preparers" element={<Preparers/>}/><Route path="/clients" element={<Clients/>}/><Route path="/apply" element={<Apply/>}/><Route path="/login" element={session?<Navigate to="/dashboard"/>:<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/dashboard" element={loading?<div className="loading">Loading secure portal…</div>:session?<Dashboard session={session}/>:<Navigate to="/login"/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
